---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: django-flux-auth
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/JesuFemi-O/flux-django

