---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: django-flux-auth
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./services/auth_service/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: django-flux-auth
  validation: client

